version: '3.9'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=sampleDBuser
    ports:
      - 3306:3306
    volumes:
    # 設定ファイル
      - ./env/conf/my.cnf:/etc/my.cnf